### ISSUE TITLE
Emacs not installed?

### ISSUE THREAD

**Issue by johnlev** [cs50spring2019/cs50-dev#2]
```
The program 'emacs' can be found in the following packages:
 * emacs24
 * emacs24-nox
 * e3
 * emacs23
 * emacs23-lucid
 * emacs23-nox
 * emacs24-lucid
 * jove
Ask your administrator to install one of them
```

**Comment by tahardi** [comment]
Hey John, I'm not familiar with emacs. Are one of those packages prefererred over others? I can easily add a command to the Vagrant file so that emacs is installed, but I want to make sure that it is the right one.

**Comment by johnlev** [comment]
I guess I am confused about all these other emacs24 things, which I have never used before. Perhaps we just need to alias the emacs command to one of these?
